// let a = 'hello world';
// console.log(a);
//  Створити змінні. Присвоїти кожному з них значення: 'hello','owu','com', 'ua', 1, 10, -999, 123, 3.14, 2.7, 16, true, false.
let a = 'hello';
let company = 'owu';
let word = 'com';
let country = 'ua';
let number = 1;
let ten = 10;
let negNumber = -999;
let sequence = 123;
let pi = 3.14;
let x = 2.7;
let y = 16;
let Yarik = true;
let Igor = false;
 // Вивести кожну змінну за допомогою: console.log , alert, document.write
console.log(a);
console.log(company);
console.log(word);
console.log(country);
console.log(number);
console.log(ten);
console.log(negNumber);
console.log(sequence);
console.log(pi);
console.log(x);
console.log(y);
console.log(Yarik);
console.log(Igor);
alert(a);
alert(company);
alert(word);
alert(country);
alert(number);
alert(ten);
alert(negNumber);
alert(sequence);
alert(pi);
alert(x);
alert(y);
alert(Yarik);
alert(Igor);
document.write(a);
document.write(company);
document.write(word);
document.write(country);
document.write(number);
document.write(ten);
document.write(negNumber);
document.write(sequence);
document.write(pi);
document.write(x);
document.write(y);
document.write(Yarik);
document.write(Igor);
// Переприсвоїти кожну змінну з завдання вище на будь які довільні значення.
a = 'bye';
company = 'wiki';
word = 'random';
country = 'us';
number = 10;
ten = 100;
negNumber = -99;
sequence = 1234;
pi = 3.1415;
x = 2.75;
y = 4;
Yarik = false;
Igor = true;